name: Add Metabolomics Data Processing Issues to Project

on:
  issues:
    types: [opened, labeled]

jobs:
  add-to-project:
    runs-on: ubuntu-latest
    if: contains(github.event.issue.labels.*.name, 'metab_data_processing')
    steps:
      - name: Add issue to project
        uses: actions/add-to-project@5afcf98fcd03f1c2f92c3c83f58ae24323cc57fd # v2.0.0
        with:
          project-url: https://github.com/orgs/microbiomedata/projects/178
          github-token: ${{ secrets.ORG_PROJECT_TOKEN }}
